### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by simklei** [FAIRdom/solr-seek-docker#2]
The FAIRDOM-SEEK documentation for [installing SEEK](https://docs.seek4science.org/tech/install.html) describes that to enable the search functionality you must setup Apache Solr. The documentation references the Docker image ([ _fairdom/seek-solr_](https://hub.docker.com/r/fairdom/seek-solr)) that this repository contains the source code for as the easiest solution for doing that.

However, I don't see any license on this repository or on the [Docker Hub page](https://hub.docker.com/r/fairdom/seek-solr). Could you please add a license?

**Comment by stuzart** [comment]
Thanks for pointing this out. I will update.
My understanding, but I'm not certain, is that the license in Github would refer to the build script and files, whereas the license for the container should be that of the solr container, since we are simply redistributing it with an additional configuration.

This would be the Apache 2.0 license, and to keep things simple I will use that for both cases

**Comment by simklei** [comment]
Thank you for the quick resolution and explanation! Since there's now a license, I'll close the issue.
